### ISSUE TITLE
No shadows are cast for small objects during solar potential calculation with "enable shadowing"= 1 or =2

### ISSUE THREAD

**Issue by AntonEberhardt** [3dgeo-heidelberg/vostok#4] opened 2022-10-12 13:50 UTC
Hey,

I have noticed that relatively small objects (for example 3x3x6m boxes) fail to cast a shadow during the solar potential calculation of vostok. Examples can be found in the attached zip-file, which contains screenshots of the issue (made using cloudcompare) and the original files used to illustrate the issues. I have experimented with making the boxes bigger and making the boxes higher, which both improved the shadow casting, but it still didn't give satisfying results. I tried different resolutions / voxel sizes (1m or 2m) and adjusted the resolution of the boxes accordingly. I also tried to change a bunch of parameters in the calculation of the normals, which did not change the result. These boxes should resemble trees in our calculation, which explains the names of the files.

I would be happy to hear from you, if you manage the reproduce this bug. I suspect it could be an issue with my normals calculation (I use cloudcompare in commandline mode), but my experiments suggest otherwise.

Best regards,
Anton Eberhardt

[vostokBug_gitIssue.zip](https://github.com/3dgeo-heidelberg/vostok/files/9765348/vostokBug_gitIssue.zip)

**Comment by omzoqasd** [comment] 2022-10-12 13:54
FYI: special interest for HEAL project

**Comment by bhoefle-3dgeo** [comment] 2022-11-03 18:30
The input files must have the format: x y z nx ny nz

Could you please just provide the input data for calculation and the config file and what you think should be the expected output. Not clear for me.

Enable shadow mode 2 also only working for the single threaded run.

**Comment by bhoefle-3dgeo** [comment] 2022-11-03 18:49
What do you mean with box? Vostok works with point clouds and cannot resemble boxes or other geometries. You would need to resample the box to e.g. 1m or 0.5m points which then cast a shadow. Right?

**Comment by AntonEberhardt** [comment] 2022-11-10 15:00
[vostok_config.txt](https://github.com/3dgeo-heidelberg/vostok/files/9981885/vostok_config.txt)
This is the config file that was used. The zip file provided above contains the test files I used for my calculations as well as the result (filenames containing "streetcloud" are the query clouds and filenames containing "pointcloud" are the pointcloud casting the shadow). With "boxes" I mean literal boxes standing on top of the query cloud. All faces of these "boxes" where filled with points according to the corresponding resolution. As far as I understood it vostok makes voxels around each point of the pointcloud, the size of these voxels is specified in line 5 of the config file. So if I have pointclouds resembling box-like objects where the faces contain for example 1 point every 2m (and having 2m voxel size specified in the config file), I would expect that these objects act  like solid walls and cast a shadow. The numerous screenshots contained in the zip file are meant to illustrate that this is not how the program behaves, since the box-like objects do not cast a solid shadow in many cases. I hope this clears it up.

Best Regards,
Anton Eberhardt

**Comment by bhoefle-3dgeo** [comment] 2022-11-10 15:58
Could you please provide a ZIP file with the exact input files and the config. Then I can reproduce it. I cannot find the input files in the config.
Did you try to create 1m spacing point clouds and then use e.g. 2m voxel size?

**Comment by AntonEberhardt** [comment] 2022-11-14 15:29
[vostokBug2.zip](https://github.com/3dgeo-heidelberg/vostok/files/10004429/vostokBug2.zip)


Here's the zipfile with the exact files. I tried increasing the voxel size, but it didn't help.

**Comment by bhoefle-3dgeo** [comment] 2022-11-14 18:47
Problem isolated. The following issue occur:

1) Your data is not prepared well to work with VOSTOK. VOSTOK is targeted to work with high-resolution 3D data (e.g. from photogrammetry or LiDAR) with "full" spatial coverage. In particular, the shadow cloud should be high-res with respect to the objects and structures of interest. In your shadow cloud you have point spacings of 1.5m, 3m and even >5m. 

2) As a follow up problem from 1) is the issue that VOSTOK is ignoring very close voxels because usually in point clouds you have some noise in the data and you do not want to the local roughness to cast shadows. This is why - unfortunately still hard-coded - in this line the first 2 voxels along the ray direction are ignored: https://github.com/3dgeo-heidelberg/vostok/blob/104a269fd9d75bd362a20714f5687c608f02e4a7/src/ShadowCalc.cpp#L132 Now, imagine big voxels sizes. This means you ignore 2*voxel_size, which could be a full tree or even building for large voxels.

Some mitigation ideas:
1) Convert your 3D model to a raster DSM (e.g. with 0.5m cell size). This will lead to higher resolution and more regular point spacing. You do not need full 3D in the shadow cloud. I also suggest to do it similarily with the other cloud (i.e. of the streets). Furthermore it will solve the problem that some of the buildings are below the terrain.

2) The step before, might already solve the problem of ignoring the closest voxels. Alternatively you can just hardcode this line to 0.001 and compile a new vostok version. If you want to contribute to VOSTOK, give also something back to the project, you can also add this as a parameter which can be set in the config file.

I will close the issue if you have understood my explanations.

**Closed as completed** 2022-11-14 18:55 UTC
